name:  pr_flow

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: ssh_gen
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.GIT_RSA }}

    - name: log_commit      
      run: |
           curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
           git config --local user.email "ravi.vasista@altair.com"
           git config --local user.name "Ravi Vasista"
           git config --global hub.protocol ssh
           bin/hub pull-request --base raviv1995:dev --head arita37:dev -m "My title"
      env:
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  
