name:  test

on:
  push:
    branches: 
      - dev


 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*

    - name: ssh_gen
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.GIT_RSA }}

    - name: log_start
      run: |
           cd /home/runner/work/mlmodels/  && git clone git@github.com:raviv1995/mlmodels_store.git  &&  ls && pwd
           cd /home/runner/work/mlmodels/mlmodels/

    - name: ml_test
      run: |
           python -c "import os; print(os)"     2>&1 | tee -a  cd /home/runner/work/mlmodels/mlmodels_store/log_$(date '+%Y-%m-%d_%H:%M:%S,%3N').txt

    - name: log_commit      
      run: |
           cd /home/runner/work/mlmodels/mlmodels_store/
           git config --local user.email "ravi.vasista@altair.com"
           git config --local user.name "Ravi Vasista"
           ls &&  git add --all &&  git commit -m "log" 
           git push origin master
  
