name:  test

on:
  push:
    branches: 
      - dev


 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*

    - name: log_start
      run: |
           cd /home/runner/work/mlmodels/  && git clone https://github.com/arita37/mlmodels_store.git  &&  ls && pwd
           cd /home/runner/work/mlmodels/mlmodels/





    - name: ml_test
      run: |
           python -c "import os; print(os)"     2>&1 | tee -a  cd /home/runner/work/mlmodels/mlmodels_store/log_$(date '+%Y-%m-%d_%H:%M:%S,%3N').txt





    - name: log_gitcommit
      run: |      
           cd /home/runner/work/mlmodels/mlmodels_store/
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           ls &&  git add --all &&  git commit -m "log" 
      
      
    - name: log_gitpush
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}    
  
